name: Generate GitHub Realtime Stats Cards

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Generate Stats SVGs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
        run: node .github/scripts/generate-stats.js

      - name: Commit and Push dist SVGs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/
          git diff --quiet && git diff --staged --quiet || (git commit -m "auto: update realtime profile SVG cards [skip ci]" && git push)
